In [65]:
from itertools import permutations
import numpy as np

def calculate_total_distance(route, distance_matrix):
    total_distance = 0
    for i in range(len(route) - 1):
        total_distance += distance_matrix[route[i]][route[i + 1]]
    total_distance += distance_matrix[route[-1]][route[0]]  # Return to the starting node
    return total_distance

def brute_force_tsp(distance_matrix):
    num_nodes = len(distance_matrix)
    nodes = list(range(num_nodes))
    optimal_route = None
    optimal_distance = float('inf')

    for perm in permutations(nodes):
        current_distance = calculate_total_distance(perm, distance_matrix)
        if current_distance < optimal_distance:
            optimal_distance = current_distance
            optimal_route = perm

    return optimal_route, optimal_distance

# Example usage

distance_matrix = [
    [0, 10, 15, 20, 25],
    [10, 0, 35, 25, 30],
    [15, 35, 0, 30, 20],
    [20, 25, 30, 0, 10],
    [25, 30, 20, 10, 0]
]

x = np.random.random((5, 5))*5
random_matrix = True
if(random_matrix):
    distance_matrix = x

optimal_route, optimal_distance = brute_force_tsp(distance_matrix)
print(f"Randowm Matris: {distance_matrix}")
print(f"Optimal Route: {optimal_route}")
print(f"Optimal Distance: {optimal_distance}")


Randowm Matris: [[1.71846465 0.4672728  4.80924077 0.95084569 4.93483119]
 [3.88883922 4.37960959 0.27845513 2.41739074 0.85295871]
 [1.91027017 4.3686269  4.22277503 4.71639495 0.73812687]
 [0.59696197 1.18090367 0.28839381 2.63052339 0.95612052]
 [2.4886474  3.12832211 0.32014192 0.18739045 3.04550354]]
Optimal Route: (0, 1, 2, 4, 3)
Optimal Distance: 2.268207215085763
