In [1]:
import numpy as np 

In [2]:
def make_block():
    block=[]
    for i in range(0, 9):
        x = np.random.choice(range(1, 10), size=(9), replace=False).tolist()
        block.append(x)
    block =  np.array(block).reshape((9, 9))
    return block

def make_col(block_9X9):
    col = []
    for i in range( 0, 9):
        for j in range(0,9):
            x = block_9X9[j][i]
            col.append(x)
    # print(col)
    col =  np.array(col).reshape((9, 9))
    return col


bulid_matris = make_block()
print(bulid_matris)
print("break")
vertikal_matris = make_col(bulid_matris)
print(vertikal_matris)






[[8 2 4 6 7 5 3 1 9]
 [8 9 1 4 2 5 3 6 7]
 [9 8 1 5 4 6 2 3 7]
 [7 9 5 6 2 4 3 8 1]
 [3 1 2 8 7 9 4 6 5]
 [4 2 9 7 1 8 6 3 5]
 [9 6 2 4 8 1 3 7 5]
 [8 2 1 3 7 5 9 4 6]
 [4 3 1 9 2 8 5 6 7]]
break
[[8 8 9 7 3 4 9 8 4]
 [2 9 8 9 1 2 6 2 3]
 [4 1 1 5 2 9 2 1 1]
 [6 4 5 6 8 7 4 3 9]
 [7 2 4 2 7 1 8 7 2]
 [5 5 6 4 9 8 1 5 8]
 [3 3 2 3 4 6 3 9 5]
 [1 6 3 8 6 3 7 4 6]
 [9 7 7 1 5 5 5 6 7]]


In [3]:
def make_block():
    block=[]
    for i in range(0, 9):
        x = np.random.choice(range(1, 10), size=(9), replace=False).tolist()
        block.append(x)
    block =  np.array(block).reshape((9, 9))
    return block

def make_col(block_9X9):
    col = []
    for i in range( 0, 9):
        for j in range(0,9):
            x = block_9X9[j][i]
            col.append(x)
    # print(col)
    col =  np.array(col).reshape((9, 9))
    return col

def make_v_m(block_9X9):
    col = []
    for i in range( 0, 9):
        for j in range(0,9):
            x = block_9X9[j][i]
            col.append(x)
    # print(col)
    col =  np.array(col).reshape((9, 9))
    return col


bulid_matris = make_block()
print(bulid_matris)
print("break")
vertikal_matris = make_col(bulid_matris)
print(vertikal_matris)

[[2 1 3 6 9 8 7 5 4]
 [4 7 6 9 1 5 8 3 2]
 [5 8 3 9 6 1 4 7 2]
 [8 1 3 6 2 4 7 9 5]
 [1 7 6 8 4 5 9 3 2]
 [5 2 4 7 6 3 9 1 8]
 [3 9 7 6 1 8 4 2 5]
 [8 1 5 9 7 3 2 4 6]
 [4 3 6 7 1 2 9 8 5]]
break
[[2 4 5 8 1 5 3 8 4]
 [1 7 8 1 7 2 9 1 3]
 [3 6 3 3 6 4 7 5 6]
 [6 9 9 6 8 7 6 9 7]
 [9 1 6 2 4 6 1 7 1]
 [8 5 1 4 5 3 8 3 2]
 [7 8 4 7 9 9 4 2 9]
 [5 3 7 9 3 1 2 4 8]
 [4 2 2 5 2 8 5 6 5]]


In [4]:
board = np.zeros((9, 9), dtype=int)
# print(board)

print(board[1])
print("H matris", bulid_matris, ) 
print("V matris",vertikal_matris )
print("zero bord ",board)

[0 0 0 0 0 0 0 0 0]
H matris [[2 1 3 6 9 8 7 5 4]
 [4 7 6 9 1 5 8 3 2]
 [5 8 3 9 6 1 4 7 2]
 [8 1 3 6 2 4 7 9 5]
 [1 7 6 8 4 5 9 3 2]
 [5 2 4 7 6 3 9 1 8]
 [3 9 7 6 1 8 4 2 5]
 [8 1 5 9 7 3 2 4 6]
 [4 3 6 7 1 2 9 8 5]]
V matris [[2 4 5 8 1 5 3 8 4]
 [1 7 8 1 7 2 9 1 3]
 [3 6 3 3 6 4 7 5 6]
 [6 9 9 6 8 7 6 9 7]
 [9 1 6 2 4 6 1 7 1]
 [8 5 1 4 5 3 8 3 2]
 [7 8 4 7 9 9 4 2 9]
 [5 3 7 9 3 1 2 4 8]
 [4 2 2 5 2 8 5 6 5]]
zero bord  [[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [5]:
start_block = np.random.choice(range(1, 10), size=9, replace=False).tolist()
board[0, :] = start_block

board[0, :] = bulid_matris[0]
board[1, :] = bulid_matris[1]

s_bord = board
v_bord = make_v_m(s_bord)
print(s_bord)
print(v_bord)

[[2 1 3 6 9 8 7 5 4]
 [4 7 6 9 1 5 8 3 2]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
[[2 4 0 0 0 0 0 0 0]
 [1 7 0 0 0 0 0 0 0]
 [3 6 0 0 0 0 0 0 0]
 [6 9 0 0 0 0 0 0 0]
 [9 1 0 0 0 0 0 0 0]
 [8 5 0 0 0 0 0 0 0]
 [7 8 0 0 0 0 0 0 0]
 [5 3 0 0 0 0 0 0 0]
 [4 2 0 0 0 0 0 0 0]]


In [6]:

# s_bord = board
# v_bord = make_v_m(s_bord)
# print(s_bord)
# print(v_bord)
# if is_valid_move(np.column_stack((H, V)), 0, col_index, r_num,0):
def is_valid_move(board, row, col, r_num,index):
    # Check the row
    if r_num in board[row, index:]:
        return False

    # Check the column
    if r_num in board[index:, col]:
        return False

    return r_num



def make_block2X2(bulid_matris,vertikal_matris):
    new_block = []
    random_raw =  np.random.choice(range(1, 10), size=9, replace=False).tolist()
    board = np.zeros((9, 9), dtype=int)
    board[0, :] =  random_raw
    print(board,"end borad")
    # v_bord = make_v_m(s_bord)
    for i in range(0,1):
        print("i:",i)
        s_bord = board
        v_bord = make_v_m(board)
        print("H",s_bord[i])
        print("v",v_bord[i])
        for j in range(0,1):
            h_board_i=board[i][j]
            v_board_i= v_bord[i][j]
            print("j",j)
            print("h_board_i",h_board_i)
            print("v_board_i",v_board_i)
            board_i =[]
            while True:
              
              r_num = np.random.randint(1, 9)
              x = is_valid_move(np.column_stack((h_board_i, v_board_i)), 0, 1, r_num,j)
              
              if x:
                  board_i.append(x)
              if len(board_i) >= 9:
                  print(board_i)
                  break
              

        #     r_num = np.random.randint(1, 10)
        #     # r_num = board[j][i]
        #     # r_num = np.random.choice(range(1, 10), size=9, replace=False).tolist()
        #     # r_num = np.random.randint(1, 10)
        #     v_num = s_bord[j][i]
        #     h_num = v_bord[j][i]
        #     new_num = board[j][i]
    #         while True:
    #             # print("x", r_num , "h",  h_num, "v",v_num)
    #             # if r_num != (h_num and v_num) and r_num not in new_block:
    #             if r_num != h_num and v_num:
    #                 new_block.append(r_num)
    #                 break
    #             else:
    #                 r_num = np.random.randint(1, 10)
    # new_block =  np.array(new_block).reshape((9, 9))
    # print(new_block)    
    # return new_block

block_3 = []
block_3 = make_block2X2(bulid_matris,vertikal_matris)


[[3 4 9 5 7 8 6 2 1]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]] end borad
i: 0
H [3 4 9 5 7 8 6 2 1]
v [3 0 0 0 0 0 0 0 0]
j 0
h_board_i 3
v_board_i 3
[8, 6, 2, 8, 6, 6, 2, 6, 4]


testing functios

In [7]:

def return_col(board, col):
    index_col = [row[col] for row in board]
    if r_num in index_col:
        return index_col

    index_col = np.array(index_col)
    index_col = index_col.tolist()
    return index_col

def return_row(board, row):
    index_col = board[row]
    index_col = np.array(index_col)
    index_col = index_col.tolist()
    return index_col

def return_num(input):
    input = np.array(input)
    input = input.tolist()
    return ', '.join(map(str, input))

# end 
a = [
    [5, 3, 7, 9, 1, 2, 6, 8,4],
    [2, 0, 0, 0, 0, 0, 0, 0,0],
    [4, 0, 0, 0, 0, 0, 0, 0,0],
    [9, 5, 0, 0, 0, 0, 0, 0,0],
    [4, 0, 0, 0, 0, 0, 0, 0,0],
    [3, 0, 0, 0, 0, 0, 0, 0,0],
    [0, 0, 0, 0, 0, 0, 0, 0,0],
    [0, 0, 0, 0, 0, 0, 0, 0,0],
    [0, 0, 0, 0, 0, 0, 0, 0,0]
]
# Example usage
H = np.array([5, 3, 7, 9, 1, 2, 6, 8, 4])
V = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0])
col = 8
row=  0
r_num = np.random.randint(1, 9)
r_num = 1
b = np.column_stack((H, V))
board = np.zeros((9, 9), dtype=int)
x = [[4, 0, 0, 0, 0, 0, 0, 0, 0], [5, 3, 7, 9, 1, 2, 6, 8, 4]]
print(return_row(a,0))
print(return_col(a,0))
print(return_num(x))

[5, 3, 7, 9, 1, 2, 6, 8, 4]
[5, 2, 4, 9, 4, 3, 0, 0, 0]
[4, 0, 0, 0, 0, 0, 0, 0, 0], [5, 3, 7, 9, 1, 2, 6, 8, 4]


In [8]:
import numpy as np

def return_num(input):
    input = np.array(input)
    input = input.tolist()
    
    # Flatten the list of lists and convert each element to a string
    flattened = ''.join(map(str, [num for sublist in input for num in sublist]))

    return [flattened]

x = [[4, 0, 0, 0, 0, 0, 0, 0, 0], [5, 3, 7, 9, 1, 2, 6, 8, 4]]
print(return_num(x))

def return_num(input):
    input = np.array(input)
    input = input.tolist()
    return ', '.join(map(str, input))
print(return_num(x))

['400000000537912684']
[4, 0, 0, 0, 0, 0, 0, 0, 0], [5, 3, 7, 9, 1, 2, 6, 8, 4]


In [9]:
def return_num(input):
    input = np.array(input)
    input = input.tolist()
    input = np.array(input)
    return input

def x_in_list(list):
    new_row = []
    RowColList = list.tolist()

    for sublist in RowColList:
        for num in range(1, 10):
            if num not in sublist:
                # print(" the new num:", num)
                new_row.append(num)
    return new_row

col = [[4, 0, 0, 0, 0, 0, 0, 0, 0]]
row = [[5, 3, 7, 9, 0, 2, 6, 8, 4]]

col = return_num(col)
row = return_num(row)
result = x_in_list(row)
print(result)

[1]


In [10]:
x = [5, 8, 9]
for i in x:
    print(i)

5
8
9


In [11]:
row = [1, 3, 4, 6]
col =  [5, 5, 5, 1,1]



# [1, 2, 5, 6, 7, 8, 9] [1, 2, 5, 6, 7, 8, 9]

def find_matching_elements(col,row):
    result=[]
    for i in col:
        if i in row:
            result.append(i)
        else:
            result.append(0)
    return result

result = find_matching_elements(col, row)
print(result)

[0, 0, 0, 1, 1]


In [22]:
import numpy as np
import random

def is_valid_move(board, row, col, num):
    
    if num in board[row]:
        return False

    # Check the column
    column_elements = [row[col] for row in board]
    if r_num in column_elements:
        return False
    return num

# end 
a = [
    [1, 2, 3, 4, 5, 6, 7, 8, 9],
    [0, 0, 0, 0, 0, 0, 0, 0,0],
    [0, 0, 0, 0, 0, 0, 0, 0,0],
    [0, 0, 0, 0, 0, 0, 0, 0,0],
    [0, 0, 0, 0, 0, 0, 0, 0,0],
    [0, 0, 0, 0, 0, 0, 0, 0,0],
    [0, 0, 0, 0, 0, 0, 0, 0,0],
    [0, 0, 0, 0, 0, 0, 0, 0,0],
    [0, 0, 0, 0, 0, 0, 0, 0,0]
]
# Example usage
H = np.array([5, 3, 7, 9, 1, 2, 6, 8, 4])
V = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0])
col = 0
row= 2
r_num = np.random.randint(1, 9)
# r_num = 10
b = np.column_stack((H, V))

board = np.zeros((9, 9), dtype=int)


    


def newList(board):
    efter_board = board
    output_board = 0
    posible_col= []
    posible_row= []
    corect_row =  []
    j = 0
    for j in range(0,9):
        # print("j",j)
        # print("j",j, efter_board[j])
        board_row = [return_row(efter_board,j)]
        row = board_row
        row = return_num(row)
        row_result = x_in_list(row) 
        posible_row.append(row_result)
        # board_col = return_col(a,0)
        add_raw_to_bord = []
        for i in range(0,9):


            # print("i",i, efter_board[j])

            board_row = [return_row(efter_board,j)]
            row = board_row
            row = return_num(row)
            row_result = x_in_list(row) 
            posible_row.append(row_result)



            # most be j to be in the top of row
            # board_col = return_col(a,0)
            col = return_col(efter_board,i)
            col = return_num([col])
            col_result = x_in_list(col)
            
            posible_col.append(col_result)
            
            # most be orgian board to find z 
            col_add = efter_board[j][i]
            corect_result = find_matching_elements(col_result, row_result)

            if col_add == 0:
                # print(i,":",col , row )
                # print(i,":",col_result , row_result )
                # print(i,":",corect_result )

                # print("i", i , corect_result )
                def remove_zeros(input_list):
                    for x in input_list:
                        if x != 0:
                            return x
                    return 0  # Return None if no non-zero element is found
                result = remove_zeros(corect_result)

                # print(result)
                # x = corect_result[0]
                x = result
                
                # print(x)
                # print(x1)
                
                # x = lenofoutput(corect_result)
                # x = corect_result[x]
                efter_board[j][i]= x
                add_raw_to_bord.append(x)
                # print( i ," : i efter:",efter_board[j] )
                # corect_row.append(efter_board[j])
    # print(add_raw_to_bord)
    # print(efter_board )
    return efter_board

board2 = np.zeros((9, 9), dtype=int)
# print(a)   
# 
a = [[0, 5, 7, 2, 9, 0, 0, 8, 0], 
     [4, 0, 0, 0, 0, 3, 0, 0, 0], 
     [0, 0, 0, 0, 0, 0, 0, 1, 0], 
     [0, 1, 4, 0, 0, 7, 0, 0, 0], 
     [5, 0, 0, 3, 0, 0, 0, 0, 9], 
     [6, 0, 3, 4, 5, 0, 1, 0, 0], 
     [0, 0, 0, 9, 3, 0, 5, 0, 1], 
     [0, 0, 0, 8, 0, 0, 0, 0, 2], 
     [2, 0, 0, 0, 0, 0, 0, 3, 0]]            
# newList(a)
print("# Sudoku before solving")
for r, line in enumerate(a):
    print(" ".join([f"{num}" if num != 0 else "_" for num in line[:3]]), "|", end=" ")
    print(" ".join([f"{num}" if num != 0 else "_" for num in line[3:6]]), "|", end=" ")
    print(" ".join([f"{num}" if num != 0 else "_" for num in line[6:]]))
    if r % 3 == 2 and r != 8:
        print("-" * 21)

print("# Sudo efter solution ")

for r, line in enumerate(newList(a)):
    print(" ".join([f"{num}" if num != 0 else "_" for num in line[:3]]), "|", end=" ")
    print(" ".join([f"{num}" if num != 0 else "_" for num in line[3:6]]), "|", end=" ")
    print(" ".join([f"{num}" if num != 0 else "_" for num in line[6:]]))
    if r % 3 == 2 and r != 8:
        print("-" * 21)

# Sudoku before solving
_ 5 7 | 2 9 _ | _ 8 _
4 _ _ | _ _ 3 | _ _ _
_ _ _ | _ _ _ | _ 1 _
---------------------
_ 1 4 | _ _ 7 | _ _ _
5 _ _ | 3 _ _ | _ _ 9
6 _ 3 | 4 5 _ | 1 _ _
---------------------
_ _ _ | 9 3 _ | 5 _ 1
_ _ _ | 8 _ _ | _ _ 2
2 _ _ | _ _ _ | _ 3 _
# Sudo efter solution 
1 5 7 | 2 9 4 | 3 8 6
4 2 1 | 5 6 3 | 7 9 8
3 4 2 | 6 7 5 | 8 1 _
---------------------
8 1 4 | _ 2 7 | 6 5 3
5 6 8 | 3 1 2 | 4 7 9
6 7 3 | 4 5 8 | 1 2 _
---------------------
7 8 6 | 9 3 _ | 5 4 1
9 3 5 | 8 4 1 | _ 6 2
2 9 _ | 1 8 6 | _ 3 4
